name: Build & Release

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust and Rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          cache: false
          rustflags: ''

      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Run Rustfmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Rust and Clippy
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
          cache: false
          rustflags: ''

      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Install WebkitGtk
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev libxdo-dev libssl-dev librsvg2-dev

      - name: Install Tailwind
        run: npm ci

      - name: Build Tailwind
        run: npm run build

      - name: Run Clippy
        run: cargo clippy

  tests:
    name: Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false
          rustflags: ''

      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Install WebkitGtk
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev libxdo-dev libssl-dev librsvg2-dev

      - name: Install Tailwind
        run: npm ci

      - name: Build Tailwind
        run: npm run build

      - name: Run tests
        run: cargo test

  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    permissions:
      actions: read
      contents: read
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false
          rustflags: ''

      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Install Dioxus CLI
        uses: taiki-e/install-action@v2
        with:
          tool: dioxus-cli

      - name: Install WebkitGtk
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev libxdo-dev libssl-dev librsvg2-dev

      - name: Install Tailwind
        run: npm ci

      - name: Build Tailwind
        run: npm run build

      - name: Bundle application
        id: bundle
        run: |
          dx bundle --release \
            --platform desktop \
            --package-types "deb" \
            --package-types "rpm" \
            --package-types "appimage" \
            --package-types "msi" \
            --package-types "dmg"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bundle-${{ matrix.os }}
          path: |
            target/dx/srednjeveski-arhivi/bundle/linux/bundle/deb/*.deb
            target/dx/srednjeveski-arhivi/bundle/linux/bundle/rpm/*.rpm
            target/dx/srednjeveski-arhivi/bundle/linux/bundle/appimage/*.AppImage
            target/dx/srednjeveski-arhivi/bundle/windows/bundle/msi/*.msi
            target/dx/srednjeveski-arhivi/bundle/macos/bundle/dmg/*.dmg
